class SendAreaChoice < ActiveHash::Base
    self.date = [
        { id: 1, choice: '---' },
        { id: 2, choice: "北海道"},
        { id: 3, choice: "青森県"},
        { id: 4, choice: "岩手県"},
        { id: 5, choice: "宮城県"},
        { id: 6, choice: "秋田県"},
        { id: 7, choice: "山形県"},
        { id: 8, choice: "福島県"},
        { id: 9, choice: "茨城県"},
        { id: 10, choice: "栃木県"},
        { id: 11, choice: "群馬県"},
        { id: 12, choice: "埼玉県"},
        { id: 13, choice: "千葉県"},
        { id: 14, choice: "東京都"},
        { id: 15, choice: "神奈川県"},
        { id: 16, choice: "新潟県"},
        { id: 17, choice: "富山県"},
        { id: 18, choice: "石川県"},
        { id: 19, choice: "福井県"},
        { id: 20, choice: "山梨県"},
        { id: 21, choice: "長野県"},
        { id: 22, choice: "岐阜県"},
        { id: 23, choice: "静岡県"},
        { id: 24, choice: "愛知県"},
        { id: 25, choice: "三重県"},
        { id: 26, choice: "滋賀県"},
        { id: 27, choice: "京都府"},
        { id: 28, choice: "大阪府"},
        { id: 29, choice: "兵庫県"},
        { id: 31, choice: "奈良県"},
        { id: 32, choice: "和歌山県"},
        { id: 33, choice: "鳥取県"},
        { id: 34, choice: "島根県"},
        { id: 35, choice: "岡山県"},
        { id: 36, choice: "広島県"},
        { id: 37, choice: "山口県"},
        { id: 38, choice: "徳島県"},
        { id: 38, choice: "香川県"},
        { id: 39, choice: "愛媛県"},
        { id: 40, choice: "高知県"},
        { id: 41, choice: "福岡県"},
        { id: 42, choice: "佐賀県"},
        { id: 43, choice: "長崎県"},
        { id: 44, choice: "熊本県"},
        { id: 45, choice: "大分県"},
        { id: 46, choice: "宮崎県"},
        { id: 47, choice: "鹿児島県"},
        { id: 48, choice: "沖縄県"}
    ]
end
